### VSCodeの REST Clientを使っての動作確認用

### 請求書登録
POST http://localhost:1323/invoice
Content-Type: application/json

{
    "userId": 1,
    "clientId": 1,
    "issueDate": "2024-12-10",
    "amount": 40000,
    "dueDate": "2024-12-31"
}


### 請求書取得
GET http://localhost:1323/invoice?startDate=2024-10-31&endDate=2024-12-31
Content-Type: application/json
